import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./_components/common/AuthProvider";
import ThemeRistry from "./_components/ThemeRegistry/ThemeRistry";
import ReduxProvider from "./_components/common/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CM Stock App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <AuthProvider>
            <ThemeRistry>{children}</ThemeRistry>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
